In [1]:
import numpy as np
import pandas as pd

In [84]:
no_series = pd.Series(np.arange(1,20))

In [85]:
no_series

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
dtype: int32

In [86]:
no_series

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
dtype: int32

In [87]:
# Masking
# no_series % 5 == 0
no_series[no_series % 5 == 0]

4      5
9     10
14    15
dtype: int32

In [90]:
# 3 and even
no_series[(no_series % 3 == 0) & (no_series % 2 == 0)]

5      6
11    12
17    18
dtype: int32

In [38]:
cities = pd.Series(['Karachi', 'Lahore', 'Islamabad', 'Murre', 'Quetta'])

In [39]:
print(cities)

0      Karachi
1       Lahore
2    Islamabad
3        Murre
4       Quetta
dtype: object

In [47]:
# cities[cities.str.len() % 3 == 0] valid method
# cities[lambda kuchbhi : kuchbhi.len() % 3 == 0 ]
cities[cities.apply(lambda kuchbhi : len(kuchbhi) % 3 == 0)]

1       Lahore
2    Islamabad
4       Quetta
dtype: object

In [52]:
fruits = pd.Series([
    '  Mango  ', 
    '  Orange  ', 
    '  Kiwi  ', 
    '  Grapes  ',
    '  Apple  ',
    '  Peach  ',
    ])

In [55]:
fruits.str.strip()

0     Mango
1    Orange
2      Kiwi
3    Grapes
4     Apple
5     Peach
dtype: object

In [60]:
fruits = fruits.apply(lambda x: x.strip())

In [65]:
fruits.apply(lambda x: len(x))
fruits.apply(len)

0    5
1    6
2    4
3    6
4    5
5    5
dtype: int64

In [92]:
# len(5) or odd
fruits[fruits.apply(lambda x: len(x) % 5 == 0 or len(x) % 2 != 0)]

0    Mango
4    Apple
5    Peach
dtype: object

In [80]:
fruits[fruits.apply(lambda x: (len(x) % 5 == 0) or (len(x) % 2 != 0))]

0    Mango
4    Apple
5    Peach
dtype: object

In [94]:
fruits[fruits.apply(lambda x: (len(x) % 5 == 0) | (len(x) % 2 != 0))]

0    Mango
4    Apple
5    Peach
dtype: object

In [98]:
fruits.name = 'Fruits'
fruits

0     Mango
1    Orange
2      Kiwi
3    Grapes
4     Apple
5     Peach
Name: Fruits, dtype: object

In [ ]:
data = {
    'Students': ['Ali', 'Hassam', 'Kashif', 'Waseem', 'Sattar'],
    'Marks': np.arange(60,65),
    'Language': ['Python', 'Javascript', 'Typescript', 'C', 'C sharp'],
}

In [113]:
df = pd.DataFrame(data)

In [114]:
df.index = ['Karachi', 'Lahore', 'Quetta', 'Murre', 'Naran']

In [115]:
df

        Students  Marks    Language
Karachi      Ali     60      Python
Lahore    Hassam     61  Javascript
Quetta    Kashif     62  Typescript
Murre     Waseem     63           C
Naran     Sattar     64     C sharp

In [107]:
test_data = {
    'Students': ['Ali', 'Hassam', 'Kashif', 'Waseem', 'Sattar'],
    # 'Marks': np.arange(60,65),
    # 'Language': ['Python', 'Javascript', 'Typescript', 'C', 'C sharp'],
}

In [110]:
pd.DataFrame(test_data)

  Students
0      Ali
1   Hassam
2   Kashif
3   Waseem
4   Sattar